// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "791e2cfa-2474-4965-b99f-91ee554547b2");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1719334423);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1719334423);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1719334423);
user_pref("app.update.lastUpdateTime.region-update-timer", 1719334423);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1719334814);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1719334423);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1719334423);
user_pref("browser.aboutwelcome.didSeeFinalScreen", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{72b68771-1132-42ae-8d75-f9efc7f4fcff}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1719334392);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 143);
user_pref("browser.newtabpage.activity-stream.impressionId", "{873ba757-65b9-4fad-b14c-c74cfda08770}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1719334394);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1719334415445");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1719336241445");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1719334406203");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1719356006203");
user_pref("browser.search.region", "CI");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20240419214016");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1719334394");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20240419214016");
user_pref("browser.startup.homepage_override.mstone", "125.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1719334814);
user_pref("browser.topsites.contile.lastFetch", 1719334814);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1719334395482");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "125.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CI");
user_pref("dom.push.userAgentID", "361c7d4c354a49018c3c0ae089fd14cd");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1719334814);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-fr@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20240419214016");
user_pref("extensions.lastAppVersion", "125.0.2");
user_pref("extensions.lastPlatformVersion", "125.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ce7a91d2-253a-41f7-98a5-fa9595605b97\",\"pictureinpicture@mozilla.org\":\"a3b8f989-a27b-4286-bc08-b732807630c5\",\"screenshots@mozilla.org\":\"f45fbce9-9171-4414-b2df-87bba46a61da\",\"webcompat-reporter@mozilla.org\":\"9b9417d7-2333-4f34-ae81-31270ca5a52a\",\"webcompat@mozilla.org\":\"470916da-6010-4046-8fb8-bd9d72877580\",\"default-theme@mozilla.org\":\"8461e45e-ef6c-452d-9643-b04729b0aee8\",\"addons-search-detection@mozilla.com\":\"082a7a87-0b74-48f8-9c48-df06c10a9de9\",\"google@search.mozilla.org\":\"a615b885-7f73-4519-aafd-72abd8be65a3\",\"wikipedia@search.mozilla.org\":\"d9d2bd67-f59b-4f2b-a3db-75e0a3cbb045\",\"bing@search.mozilla.org\":\"8af8abe3-5345-4d8e-9ef8-bcabd1725682\",\"ddg@search.mozilla.org\":\"5e16a750-4c75-4ce8-a719-75c2ec4a09aa\",\"ebay@search.mozilla.org\":\"29655c90-15cd-4943-937c-51c7f7445c01\",\"qwant@search.mozilla.org\":\"ba370505-c35a-4947-ab4d-dfdd03106a0b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: null, errorCode: 5, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1719334424);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1719334424);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("memory.phc.enabled", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2024-06-25T16:53:15.427Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "14da7a2a-98c9-4e9f-800e-608a88d4cdd5");
user_pref("services.settings.blocklists.addons-bloomfilters.last_check", 1719334423);
user_pref("services.settings.blocklists.gfx.last_check", 1719334423);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1719334423);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1719334423);
user_pref("services.settings.main.devtools-devices.last_check", 1719334423);
user_pref("services.settings.main.doh-config.last_check", 1719334423);
user_pref("services.settings.main.doh-providers.last_check", 1719334423);
user_pref("services.settings.main.hijack-blocklists.last_check", 1719334423);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1719334423);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1719334423);
user_pref("services.settings.main.pioneer-study-addons-v1.last_check", 1719334423);
user_pref("services.settings.main.search-telemetry-v2.last_check", 1719334423);
user_pref("services.settings.main.sites-classification.last_check", 1719334423);
user_pref("services.settings.main.top-sites.last_check", 1719334423);
user_pref("services.settings.main.websites-with-shared-credential-backends.last_check", 1719334423);
user_pref("toolkit.startup.last_success", 1719334812);
user_pref("toolkit.telemetry.cachedClientID", "b8b51870-85ad-4c1a-ac7c-d1be31a92ada");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20240419214016");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
